/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lamnt.ui;

import com.lamnt.util.Auth;
import com.lamnt.util.MsgBox;
import com.lamnt.util.XImage;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author DELL
 */
public class mainscreenJFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainscreenJFrame
     */
    public mainscreenJFrame() {
        initComponents();
        init();
    }
    void init(){
        setIconImage(XImage.getAppIcon());
        setLocationRelativeTo(null);
        new ChaoJDialog(this,true).setVisible(true);
        new LoginJDialog(this,true).setVisible(true);
        getContentPane().setBackground(Color.white);
        new Timer(1000,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();  
                SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");
                String text = formater.format(now);
                lblclock.setText(text);
            }
        }).start();
    }
    void openHuongDan(){
           try{
               Desktop.getDesktop().browse(new File("help/about.html").toURI());
           }
           catch(IOException ex){
               MsgBox.alert(this,"Không Tìm Thấy File Hướng Dẫn");
           }
       }
    void dangXuat(){
        Auth.clear();//authentication 
        this.dispose();
    }
    void ketThuc(){
        if(MsgBox.confirm(this, "Bạn muốn kết thúc làm việc?")){
            System.exit(0);
        }
    }
    void openDangnhap(){
         if(Auth.isLogin()){
            new LoginJDialog(this, true).setVisible(true);
        }
        else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    void openDoiMatKhau() {
        if(Auth.isLogin()){//kiểm tra người dùng đã dắng nhập ? 
            new CRPJDialog(this, true).setVisible(true);
        }
        else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
        new LoginJDialog(this, true).setVisible(true);
    }
    void openNguoiDung(){
        if(Auth.isLogin()){//kiểm tra người dùng đã dắng nhập ? 
            new NguoiDungJDialog(this, true).setVisible(true);
        }
        else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    void openDocGia(){
        if(Auth.isLogin()){//kiểm tra người dùng đã dắng nhập ? 
            new DocGiaJDialog(this, true).setVisible(true);
        }
        else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
   }
   void openSach(){
        if(Auth.isLogin()){
            new SachJDialog(this, true).setVisible(true);
       }
        else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
   void openPM(){
        if(Auth.isLogin()){
            new CTPMJDialog(this, true).setVisible(true);
       }
        else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
   void openCTPM(){
       if(Auth.isLogin()){
            new PMJDialog(this, true).setVisible(true);
       }
        else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
   }
   void openThongKe(int index){
           if(Auth.isLogin()){
               if(index == 1&&!Auth.isManager()){
                   MsgBox.alert(this,"Bạn không có quyền xem thông tin doanh thu");
                   return;
               }else{
                   ThongKeJDialog tkwin = new ThongKeJDialog(this,true);
                   tkwin.setVisible(true);
                   tkwin.selectTab(index);
               }
           }else{
               MsgBox.alert(this,"Vui lòng đăng nhập lại");
           }
       }
    void openQLLoaiSach(){
        if(Auth.isLogin()){
            new LoaiSachJDialog(this, true).setVisible(true);
       }
        else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    void openMail(){
        if(Auth.isLogin()){
            new SendMailJDialog(this, true).setVisible(true);
       }
        else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblhienthi = new javax.swing.JButton();
        lblclock = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblmn1 = new javax.swing.JLabel();
        lblQLS = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblmn2 = new javax.swing.JLabel();
        lblQLDG = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblmn3 = new javax.swing.JLabel();
        QLND = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblmn4 = new javax.swing.JLabel();
        QLPM = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblDx = new javax.swing.JLabel();
        lblkt = new javax.swing.JLabel();
        pnlview = new javax.swing.JPanel();
        lblmn5 = new javax.swing.JLabel();
        lblQLS1 = new javax.swing.JLabel();
        pnlview1 = new javax.swing.JPanel();
        lblmn6 = new javax.swing.JLabel();
        lblQLS2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnidangnhap = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnidangxuat = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniketthuc = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniPM = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mniQLSach = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        mniQLSV = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniQLND = new javax.swing.JMenuItem();
        mnutk = new javax.swing.JMenu();
        mniThongKe = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mniThongKe2 = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnihuondan = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mniinfo = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ THƯ VIỆN");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lblhienthi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Print.png"))); // NOI18N
        lblhienthi.setText("Ứng Dụng Người Dùng");
        lblhienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblhienthiActionPerformed(evt);
            }
        });

        lblclock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Clock.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblhienthi, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblclock, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblclock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblhienthi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/BOOK-LIBRAY.jpg"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        lblmn1.setBackground(new java.awt.Color(192, 27, 54));
        lblmn1.setOpaque(true);

        lblQLS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQLS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQLS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/bk1.png"))); // NOI18N
        lblQLS.setText("Quản Lý Sách");
        lblQLS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLSMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblmn1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQLS, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLS))
        );

        lblmn2.setBackground(new java.awt.Color(192, 27, 54));
        lblmn2.setOpaque(true);

        lblQLDG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQLDG.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQLDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/st1.png"))); // NOI18N
        lblQLDG.setText("Quản Lý Độc Giả");
        lblQLDG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLDGMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lblmn2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQLDG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLDG))
        );

        lblmn3.setBackground(new java.awt.Color(192, 27, 54));
        lblmn3.setOpaque(true);

        QLND.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QLND.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        QLND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/u.png"))); // NOI18N
        QLND.setText("Quản Lý Người Dùng");
        QLND.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QLNDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lblmn3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QLND, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QLND)
                .addContainerGap())
        );

        lblmn4.setBackground(new java.awt.Color(192, 27, 54));
        lblmn4.setOpaque(true);

        QLPM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QLPM.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        QLPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/bill.png"))); // NOI18N
        QLPM.setText("Quản Lý Phiếu Mượn");
        QLPM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QLPMMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(lblmn4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QLPM, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QLPM)
                .addContainerGap())
        );

        lblDx.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Pointer.png"))); // NOI18N
        lblDx.setText("Đăng Xuất");
        lblDx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDxMouseClicked(evt);
            }
        });

        lblkt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblkt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblkt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Stop.png"))); // NOI18N
        lblkt.setText("Kết Thúc");
        lblkt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblktMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblkt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDx, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addGap(0, 89, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblkt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlviewMouseClicked(evt);
            }
        });

        lblmn5.setBackground(new java.awt.Color(192, 27, 54));
        lblmn5.setOpaque(true);

        lblQLS1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQLS1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQLS1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Book.png"))); // NOI18N
        lblQLS1.setText("Quản Lý Loại Sách");
        lblQLS1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLS1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlviewLayout = new javax.swing.GroupLayout(pnlview);
        pnlview.setLayout(pnlviewLayout);
        pnlviewLayout.setHorizontalGroup(
            pnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlviewLayout.createSequentialGroup()
                .addComponent(lblmn5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQLS1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
        );
        pnlviewLayout.setVerticalGroup(
            pnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLS1)
                .addContainerGap())
        );

        pnlview1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlview1MouseClicked(evt);
            }
        });

        lblmn6.setBackground(new java.awt.Color(192, 27, 54));
        lblmn6.setOpaque(true);

        lblQLS2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQLS2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQLS2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/List.png"))); // NOI18N
        lblQLS2.setText("THỐNG KÊ");
        lblQLS2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLS2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlview1Layout = new javax.swing.GroupLayout(pnlview1);
        pnlview1.setLayout(pnlview1Layout);
        pnlview1Layout.setHorizontalGroup(
            pnlview1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlview1Layout.createSequentialGroup()
                .addComponent(lblmn6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQLS2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlview1Layout.setVerticalGroup(
            pnlview1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pnlview1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLS2))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlview1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(pnlview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(pnlview1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HỆ THỐNG QUẢN LÝ THƯ VIỆN");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Software.png"))); // NOI18N
        jMenu1.setText("Hệ Thống");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mnidangnhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnidangnhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnidangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Login.png"))); // NOI18N
        mnidangnhap.setText("ĐĂNG NHẬP");
        mnidangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidangnhapActionPerformed(evt);
            }
        });
        jMenu1.add(mnidangnhap);
        jMenu1.add(jSeparator2);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Refresh.png"))); // NOI18N
        jMenuItem2.setText("ĐỔI MẬT KHẨU");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator3);

        mnidangxuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnidangxuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnidangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Lock.png"))); // NOI18N
        mnidangxuat.setText("ĐĂNG XUẤT");
        mnidangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidangxuatActionPerformed(evt);
            }
        });
        jMenu1.add(mnidangxuat);
        jMenu1.add(jSeparator4);

        mniketthuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniketthuc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mniketthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/sach.png"))); // NOI18N
        mniketthuc.setText("KẾT THÚC");
        mniketthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniketthucActionPerformed(evt);
            }
        });
        jMenu1.add(mniketthuc);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Mouse.png"))); // NOI18N
        jMenu2.setText("Quản Lý");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mniPM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniPM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mniPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Bookmark.png"))); // NOI18N
        mniPM.setText("Chi Tiết Phiếu Mượn");
        mniPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPMActionPerformed(evt);
            }
        });
        jMenu2.add(mniPM);
        jMenu2.add(jSeparator8);

        mniQLSach.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniQLSach.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mniQLSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Book.png"))); // NOI18N
        mniQLSach.setText("Quản Lý Sách");
        mniQLSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLSachActionPerformed(evt);
            }
        });
        jMenu2.add(mniQLSach);
        jMenu2.add(jSeparator9);

        mniQLSV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniQLSV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mniQLSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Notes.png"))); // NOI18N
        mniQLSV.setText("Quản Lý Độc Giả");
        mniQLSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLSVActionPerformed(evt);
            }
        });
        jMenu2.add(mniQLSV);
        jMenu2.add(jSeparator5);

        mniQLND.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniQLND.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mniQLND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Boy.png"))); // NOI18N
        mniQLND.setText("Quản Lý Người Dùng");
        mniQLND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLNDActionPerformed(evt);
            }
        });
        jMenu2.add(mniQLND);

        jMenuBar1.add(jMenu2);

        mnutk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Statistics.png"))); // NOI18N
        mnutk.setText("Thống Kê");
        mnutk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mniThongKe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Wireless.png"))); // NOI18N
        mniThongKe.setText("Thống Kê Tổng Hợp");
        mniThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThongKeActionPerformed(evt);
            }
        });
        mnutk.add(mniThongKe);
        mnutk.add(jSeparator7);

        mniThongKe2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniThongKe2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Clipboard.png"))); // NOI18N
        mniThongKe2.setText("Thống Kê Phiếu Mượn");
        mniThongKe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThongKe2ActionPerformed(evt);
            }
        });
        mnutk.add(mniThongKe2);

        jMenuBar1.add(mnutk);

        mnuHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Help.png"))); // NOI18N
        mnuHelp.setText("Trợ Giúp");
        mnuHelp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mnihuondan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnihuondan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnihuondan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Color wheel.png"))); // NOI18N
        mnihuondan.setText("Hướng Dẫn");
        mnihuondan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnihuondanActionPerformed(evt);
            }
        });
        mnuHelp.add(mnihuondan);
        mnuHelp.add(jSeparator6);

        mniinfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniinfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mniinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Info.png"))); // NOI18N
        mniinfo.setText("Giới Thiệu");
        mniinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniinfoActionPerformed(evt);
            }
        });
        mnuHelp.add(mniinfo);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Mail.png"))); // NOI18N
        jMenuItem1.setText("Mail");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuHelp.add(jMenuItem1);

        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblhienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblhienthiActionPerformed
        // TODO add your handling code here:
        String str = "Program FPT FPOLY Dự Án 1";
        str+="\nEmployees: Nguyễn Trung Lam";
        str+="\nEmployees: Lê Trường Giang";
        str+="\nApplication: Nhóm 5 - Quản Lý Dự Án Thư Viện";
        str+="\nLast Update:10-11-2021";
        JOptionPane.showMessageDialog(null,str,"Nhóm Làm Ứng Dụng",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_lblhienthiActionPerformed

    private void mnihuondanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnihuondanActionPerformed
        // TODO add your handling code here:
        this.openHuongDan();
    }//GEN-LAST:event_mnihuondanActionPerformed

    private void mniinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniinfoActionPerformed
        // TODO add your handling code here:
        iteJDialog ite = new iteJDialog(this,true);
        ite.setVisible(true);
    }//GEN-LAST:event_mniinfoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.openDoiMatKhau();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnidangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidangxuatActionPerformed
        // TODO add your handling code here:
        this.dangXuat();
    }//GEN-LAST:event_mnidangxuatActionPerformed

    private void mniketthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniketthucActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mniketthucActionPerformed

    private void mnidangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidangnhapActionPerformed
        // TODO add your handling code here:
        this.openDangnhap();
    }//GEN-LAST:event_mnidangnhapActionPerformed

    private void mniQLNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLNDActionPerformed
        // TODO add your handling code here:
        this.openNguoiDung();
    }//GEN-LAST:event_mniQLNDActionPerformed

    private void mniQLSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLSVActionPerformed
        // TODO add your handling code here:
        this.openDocGia();
    }//GEN-LAST:event_mniQLSVActionPerformed

    private void mniQLSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLSachActionPerformed
        // TODO add your handling code here:
       this.openSach();
    }//GEN-LAST:event_mniQLSachActionPerformed

    private void lblQLSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLSMouseClicked
        // TODO add your handling code here:
        this.openSach();
    }//GEN-LAST:event_lblQLSMouseClicked

    private void lblQLDGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLDGMouseClicked
        // TODO add your handling code here:
        this.openDocGia();
    }//GEN-LAST:event_lblQLDGMouseClicked

    private void QLNDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLNDMouseClicked
        // TODO add your handling code here:
        this.openNguoiDung();
    }//GEN-LAST:event_QLNDMouseClicked

    private void lblktMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblktMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblktMouseClicked

    private void lblDxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDxMouseClicked
        // TODO add your handling code here:
        this.dangXuat();
    }//GEN-LAST:event_lblDxMouseClicked

    private void lblQLS1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLS1MouseClicked
        // TODO add your handling code here:
        this.openQLLoaiSach();
    }//GEN-LAST:event_lblQLS1MouseClicked

    private void pnlviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlviewMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlviewMouseClicked

    private void mniPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPMActionPerformed
        // TODO add your handling code here:
        openCTPM();
    }//GEN-LAST:event_mniPMActionPerformed

    private void QLPMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QLPMMouseClicked
        // TODO add your handling code here:
        this.openPM();
    }//GEN-LAST:event_QLPMMouseClicked

    private void mniThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThongKeActionPerformed
        // TODO add your handling code here:
        this.openThongKe(1);
    }//GEN-LAST:event_mniThongKeActionPerformed

    private void lblQLS2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLS2MouseClicked
        // TODO add your handling code here:
        this.openThongKe(1);
    }//GEN-LAST:event_lblQLS2MouseClicked

    private void pnlview1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlview1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlview1MouseClicked

    private void mniThongKe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThongKe2ActionPerformed
        // TODO add your handling code here:
        this.openThongKe(1);
    }//GEN-LAST:event_mniThongKe2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.openMail();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainscreenJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainscreenJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainscreenJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainscreenJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainscreenJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel QLND;
    private javax.swing.JLabel QLPM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JLabel lblDx;
    private javax.swing.JLabel lblQLDG;
    private javax.swing.JLabel lblQLS;
    private javax.swing.JLabel lblQLS1;
    private javax.swing.JLabel lblQLS2;
    private javax.swing.JButton lblclock;
    private javax.swing.JButton lblhienthi;
    private javax.swing.JLabel lblkt;
    private javax.swing.JLabel lblmn1;
    private javax.swing.JLabel lblmn2;
    private javax.swing.JLabel lblmn3;
    private javax.swing.JLabel lblmn4;
    private javax.swing.JLabel lblmn5;
    private javax.swing.JLabel lblmn6;
    private javax.swing.JMenuItem mniPM;
    private javax.swing.JMenuItem mniQLND;
    private javax.swing.JMenuItem mniQLSV;
    private javax.swing.JMenuItem mniQLSach;
    private javax.swing.JMenuItem mniThongKe;
    private javax.swing.JMenuItem mniThongKe2;
    private javax.swing.JMenuItem mnidangnhap;
    private javax.swing.JMenuItem mnidangxuat;
    private javax.swing.JMenuItem mnihuondan;
    private javax.swing.JMenuItem mniinfo;
    private javax.swing.JMenuItem mniketthuc;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnutk;
    private javax.swing.JPanel pnlview;
    private javax.swing.JPanel pnlview1;
    // End of variables declaration//GEN-END:variables
}
