/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lamnt.ui;

import com.lamnt.helper.DialogHelper;
import com.lamnt.util.XDate;
import com.lamnt.util.XImage;
import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import com.lamnt.entity.NguoiDung;
import com.lamnt.dao.NguoiDungDAO;
import com.lamnt.util.Auth;
import com.lamnt.util.MsgBox;
import java.text.SimpleDateFormat;

/**
 *
 * @author DELL
 */
public class NguoiDungJDialog extends javax.swing.JDialog {
    int row = -1;// Hàng đc chọn hiện tại trên bảng
    NguoiDungDAO dao = new NguoiDungDAO();
    /**
     * Creates new form NguoiDungJDialog
     */
    public NguoiDungJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    void init(){
        getContentPane().setBackground(Color.white);
        setIconImage(XImage.getAppIcon());// sử dụng lớp tiện ích XImage để đọc và chọn file ảnh
        setLocationRelativeTo(null);// dùng câu lệnh để đưa form ra giữa màn hình
        fillTable();// đổ dữ liệu lên Jtable
        updateStatus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaND = new javax.swing.JTextField();
        txthoten = new javax.swing.JTextField();
        txtQueQuan = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        txtxacnhanmatkhau = new javax.swing.JPasswordField();
        txtLuong = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        rdoQuanLy = new javax.swing.JRadioButton();
        rdoNhanVien = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        btnthem = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        chOnMK = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNguoiDung = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("QUẢN LÝ NGƯỜI DÙNG");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Quản Lý Người Dùng ");

        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Mã ND:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Họ Và Tên:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Ngày Sinh:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Quê Quán:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Số Điện Thoại");

        txtMaND.setNextFocusableComponent(txthoten);

        txthoten.setNextFocusableComponent(txtNgaySinh);

        txtQueQuan.setNextFocusableComponent(txtsdt);

        txtNgaySinh.setNextFocusableComponent(txtQueQuan);

        txtsdt.setNextFocusableComponent(txtMatKhau);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Mật Khẩu:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Xác Nhận Mật Khẩu:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Lương:");

        txtMatKhau.setNextFocusableComponent(txtxacnhanmatkhau);

        txtxacnhanmatkhau.setNextFocusableComponent(txtLuong);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Giới Tính:");

        buttonGroup1.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdoNam.setSelected(true);
        rdoNam.setText("Nam");
        rdoNam.setNextFocusableComponent(rdoNu);

        buttonGroup1.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdoNu.setText("Nữ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Vai Trò:");

        buttonGroup2.add(rdoQuanLy);
        rdoQuanLy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdoQuanLy.setSelected(true);
        rdoQuanLy.setText("Quản Lý");
        rdoQuanLy.setNextFocusableComponent(rdoNu);

        buttonGroup2.add(rdoNhanVien);
        rdoNhanVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdoNhanVien.setText("Nhân Viên");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnthem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Add.png"))); // NOI18N
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Refresh.png"))); // NOI18N
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnsua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Upload.png"))); // NOI18N
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/Delete.png"))); // NOI18N
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnclear)
                    .addComponent(btnthem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxoa)
                    .addComponent(btnsua))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Điều Khiển", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnPrev.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/prev.png"))); // NOI18N
        btnPrev.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/next.png"))); // NOI18N
        btnNext.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnFirst.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/first.png"))); // NOI18N
        btnFirst.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnLast.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lamnt/icons/last.png"))); // NOI18N
        btnLast.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrev)
                    .addComponent(btnNext)
                    .addComponent(btnLast)
                    .addComponent(btnFirst))
                .addContainerGap())
        );

        chOnMK.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        chOnMK.setText("Hiển Thị Mật Khẩu");
        chOnMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chOnMKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chOnMK)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel10))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMaND, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(125, 125, 125)
                                            .addComponent(jLabel7)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMatKhau)
                                        .addComponent(txtxacnhanmatkhau)
                                        .addComponent(txtLuong)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rdoNam, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdoNu, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdoQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(rdoNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaND, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(txtMatKhau))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addComponent(txtxacnhanmatkhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chOnMK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(txtLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(rdoNam)
                            .addComponent(rdoNu))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(rdoQuanLy)
                            .addComponent(rdoNhanVien))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );

        tabs.addTab("CẬP NHẬT", jPanel1);

        tblNguoiDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã ND", "Họ Tên", "Mật Khẩu", "Giới Tính", "Ngày Sinh", "SĐT", "Quê Quán", "Lương", "Vai Trò"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNguoiDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblNguoiDungMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblNguoiDung);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tabs.addTab("DANH SÁCH", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblNguoiDungMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNguoiDungMousePressed
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            this.row = tblNguoiDung.rowAtPoint(evt.getPoint());
            tabs.setSelectedIndex(0);// chọn tabs danh sách để chọn từng chuyên đề
            this.edit();// khi pressed thì sẽ đổ dữ liệu qua tab cập nhật
        }
    }//GEN-LAST:event_tblNguoiDungMousePressed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if (isValidated(true)) {// kiểm tra nhập liệu 
            insert();
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        if (isValidated(false)) {// kiểm tra nhập liệu 
            update();
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        this.Prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        this.Next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        this.First();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        this.Last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void chOnMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chOnMKActionPerformed
        // TODO add your handling code here:
        if(chOnMK.isSelected()){
            txtxacnhanmatkhau.setEchoChar((char)0);
        }else{
            txtxacnhanmatkhau.setEchoChar('*');
        }
    }//GEN-LAST:event_chOnMKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NguoiDungJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NguoiDungJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NguoiDungJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NguoiDungJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NguoiDungJDialog dialog = new NguoiDungJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox chOnMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNhanVien;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JRadioButton rdoQuanLy;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblNguoiDung;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMaND;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JPasswordField txtxacnhanmatkhau;
    // End of variables declaration//GEN-END:variables
    void fillTable(){// đổ dữ liệu vào tblNguoiDung
        DefaultTableModel model = (DefaultTableModel)tblNguoiDung.getModel();
        model.setRowCount(0);//Xoa tat ca hang trong jtable
            try {
            List<NguoiDung> list = dao.selectAll(); // đổ dữ liệu từ CSDL
            for (NguoiDung nd : list) {
            Object[] row = {
                    nd.getMaND(),
                    nd.getHoTen(),
                    nd.getMatKhau().replaceAll(nd.getMatKhau(), "******"),// dùng replace để che mật khẩu 
                    nd.getGioiTinh() ? "Nam" : "Nữ",
                    XDate.toString(nd.getNgaySinh()),
                    nd.getDienThoai(),
                    nd.getQueQuan(),
                    nd.getLuong(),
                    nd.getVaiTro()?"Quản Lý":"Nhân viên"// trưởng phòng, nhân viên đang đăng nhập 
                };
                    model.addRow(row);//thêm 1 hàng vào jtable
                }
            }
         catch(Exception e){
             DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");// trả về thông báo nếu lỗi dữ liệu
            }
        }
    void edit(){// khi double click vào bảng nhân viên
        try{
            String mand = (String)tblNguoiDung.getValueAt(this.row,0);
            NguoiDung nd = dao.selectById(mand);// sử dụng câu lệnh slectByid để chọn từng nhân viên trong Jtable
            if(nd != null){
            setForm(nd);
            tabs.setSelectedIndex(0);// khi pressed vào bảng thì chuyển qua bảng cập nhật
         }
        }catch (Exception e){
                MsgBox.alert(this,"Lỗi Truy Vấn Dữ Liệu");// đưa ra thông báo lỗi truy vấn dữ liệu
          }
        this.updateStatus();// trả về trạng thái form như ban đầu 
        }
    void updateStatus(){
         boolean edit = this.row >=0;// người ta đang chọn hàng ở đâu đó (true là chọn, false là không chọn)
         boolean first = this.row == 0;// đang ở bảng ghi đầu tiên
         boolean last = this.row == tblNguoiDung.getRowCount() - 1;// đang ở vị trí cuối cùng
         txtMaND.setEditable(!edit);
         //Trạng Thái Form
        //Khi insert thì không update và delete
        btnthem.setEnabled(!edit);// nếu giá trị edit là false thì mới cho sửa
        btnsua.setEnabled(edit);// nếu giá trị edit là false thì mới nỗi button lên cho ta chọn
        btnxoa.setEnabled(edit);// nếu giá trị edit là true sẽ bật Enabled lên (có nghĩa là mờ nút đi),(có nghĩa là trên form có thông tin)
        //Trạng thái điều hướng
        btnFirst.setEnabled(edit && !first);// nếu như giá trị edit là true và ko phải hàng đầu tiên thì nó sẽ ẩn
        btnPrev.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);// nếu như giá trị edit là true và ko phải hàng cuối cùng thì nó sẽ ẩn
        btnLast.setEnabled(edit && !last);
    }
    void clearForm(){// khi chúng ta nhấn mới/ thì sẽ trả về trạng thái fomr ban đầu
        NguoiDung nd = new NguoiDung();
        this.setForm(nd);  
        txtNgaySinh.setText("");
        txtLuong.setText("");
        this.row = -1;
        this.updateStatus();
    }
    void setForm(NguoiDung nd){//là lấy thông tin 1 nv có sẵn hiện lên trên form
        txtMaND.setText(nd.getMaND());
        txthoten.setText(nd.getHoTen());
        txtQueQuan.setText(nd.getQueQuan());
        txtsdt.setText(nd.getDienThoai());
        txtMatKhau.setText(nd.getMatKhau());
        txtxacnhanmatkhau.setText(nd.getMatKhau());
        if (nd.getGioiTinh()!=null){
            rdoNam.setSelected(true);
        }
        else{
            rdoNu.setSelected(true);
        }
        if(nd.getVaiTro()!=null){
            rdoQuanLy.setSelected(true);
        }
        else{
            rdoNhanVien.setSelected(true);
        }
        txtNgaySinh.setText(XDate.toString(nd.getNgaySinh(),"dd/MM/yyyy"));
        if (nd.getLuong() != null) {
            txtLuong.setText(Double.toString(nd.getLuong()));
        }
    }
    NguoiDung getForm(){// lấy ra 1 nhân viên từ thông tin nhập trên form, cho nên dòng đầu tiên phải tạo ra 1 nv mới
        NguoiDung nd = new NguoiDung();
        nd.setMaND(txtMaND.getText());
        nd.setHoTen(txthoten.getText());
        nd.setNgaySinh(XDate.toDate(txtNgaySinh.getText(),"dd/MM/yyyy"));//sử dụng lớp tiện ích XDate
        nd.setQueQuan(txtQueQuan.getText());
        nd.setDienThoai(txtsdt.getText());
        nd.setMatKhau(txtMatKhau.getText());
        nd.setLuong(Double.parseDouble(txtLuong.getText()));
        nd.setGioiTinh(rdoNam.isSelected());
        nd.setVaiTro(rdoQuanLy.isSelected());
        return nd;
    }
    void insert(){
        NguoiDung nd = getForm();
        String mk2 = new String(txtxacnhanmatkhau.getPassword());
        if(mk2.equals(nd.getMatKhau())){
            try{
                dao.insert(nd);// sử dụng câu lệnh insert dao nhân viên để thêm vào csdl
                this.fillTable();// đổ nhân viên vừa thêm vào Jtable
                this.clearForm();// khi thêm xong và xóa trắng các dòng
                MsgBox.alert(this,"Thêm Mới Thành Công ");// đưa ra thông báo
            }catch(Exception e){
                //e.printStackTrace();
                MsgBox.alert(this, "Thêm Mới Thất Bại");
            }
        }else{
            MsgBox.alert(this, "Xác Nhận Mật Khẩu Đúng");
        }
     }
    void update(){
        NguoiDung nv = getForm();
        String mk2 = new String(txtxacnhanmatkhau.getPassword());
        if(mk2.equals(nv.getMatKhau())){
            try{
                dao.update(nv);// sử dụng câu lệnh update để sửa 1 nhân viên hoặc trưởng phòng từ csdl
                this.fillTable();// đổ nhân viên vừa thêm vào Jtable
                this.clearForm();//khi sửa xong và xóa trắng các dòng
                MsgBox.alert(this,"Cập Nhật Thành Công");
            }catch(Exception e){
                //e.printStackTrace();
                MsgBox.alert(this, "Cập Nhật Thất Bại");// sử dụng lớp tiện ích mgsbox.aleert để đưa ra thông báo 
            }
        }else{
            MsgBox.alert(this, "Xác Nhận Mật Khẩu Không Đúng");
        }
    }
    void delete(){
        if(!Auth.isManager()){// nếu ko phải tp thì báo 
            MsgBox.alert(this, "Bạn không có quyền xóa người dùng!");
        }
        else{
            String manv = txtMaND.getText();
            if(manv.equals(Auth.user.getMaND())){
                MsgBox.alert(this, "Bạn không được xóa chính bạn!");
            }
            else if(MsgBox.confirm(this, "Bạn thực sự muốn xóa người dùng này?")){
                try {
                    dao.delete(manv);// sử dụng câu lệnh delete để xóa 1 nhân viên hoặc trưởng phòng từ csdl
                    this.fillTable();//xóa nhân viên vừa xóa trong Jtable
                    this.clearForm();//xóa trắng các dòng trong bảng cập nhật
                    MsgBox.alert(this, "Xóa thành công!");// sử dụng lớp tiện ích mgsbox.aleert để đưa ra thông báo 
                } 
                catch (Exception e) {
                    MsgBox.alert(this, "Xóa thất bại!");
                }
            }
        }
    }
    void First(){
        this.row = 0;
        this.edit();
    }
    void Last(){
        this.row = tblNguoiDung.getRowCount() - 1;
        this.edit();
    }
    void Next(){
        if(row < tblNguoiDung.getRowCount()-1){
            row++;
            edit();
        }
    }
    void Prev(){
        if (row >0) {
            row --;
            edit();
        }   
    }
    public boolean isValidated(boolean chk){// kiểm tra nhập liệu
        List<NguoiDung> list = dao.selectAll();
        if (chk) {
            for (NguoiDung nd : list) {
                if (txtMaND.getText().equalsIgnoreCase(nd.getMaND())) {
                    MsgBox.alert(this, "Mã nhân viên đã tồn tại");// nếu mã đã có thì trả về thông báo
                    txtMaND.requestFocus();//ứng dụng vào việc click nhập 
                    //liệu thì các dữ liệu khác có đúng yêu cầu hay chưa.
                    return false;
                }
            }
        }
        try {
            if (txtMaND.getText().length() == 0) {
                MsgBox.alert(this, "Không được phép để trống họ tên!");
                 txtMaND.requestFocus();
                return false;
            } else if (txtMaND.getText().length() > 10) {
                MsgBox.alert(this, "Mã không được quá 10 ký tự!");
                txtMaND.requestFocus();
                return false;
            } else if (txthoten.getText().length() == 0) {
                MsgBox.alert(this, "Không được phép để trống họ tên!");
                txthoten.requestFocus();
                return false;
            } else if (!txthoten.getText().matches("[^0-9]+")) {
                MsgBox.alert(this, "Trong họ tên không được có số!");
                txthoten.requestFocus();
                return false;
            } else if (txtQueQuan.getText().length() == 0) {
                MsgBox.alert(this, "Không được phép để trống quê quán!");
                txtQueQuan.requestFocus();
                return false;
            } else if (txtsdt.getText().length() == 0) {
                MsgBox.alert(this, "Không được phép để trống số điện thoại!");
                 txtsdt.requestFocus();
                return false;
            } else if (txtMatKhau.getText().length() == 0) {
                MsgBox.alert(this, "Không được phép để trống mật khẩu!");
                txtMatKhau.requestFocus();
                return false;
            } else if (txtxacnhanmatkhau.getText().length() == 0) {
                MsgBox.alert(this, "Bạn chưa xác nhận lại mật khẩu!");
                txtMatKhau.requestFocus();
                return false;
            } else if (txtLuong.getText().length() == 0) {
                MsgBox.alert(this, "Bạn chưa nhập lương!");
                txtLuong.requestFocus();
                return false;
            } else if (Double.parseDouble(txtLuong.getText()) <= 0) {
                MsgBox.alert(this, "Lương Phải nhập bằng số dương!");
                txtLuong.requestFocus();
                return false;
            }
        } catch (Exception e) {
                MsgBox.alert(this, "Lương Phải nhập bằng số!");
                return false;
        }
        return true;
    }
}
